url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: betterplace.org Direkt
email: support@betterplace.org
description: "Spenden Sammeln - Einfach und direkt"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/betterplace_org
  - title: facebook
    url: https://www.facebook.com/betterplace.org
  - title: instagram
    url: https://www.instagram.com/betterplace_org/


# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
